### ISSUE TITLE
Create a react application with a vite template

### ISSUE THREAD

**Issue by erwanriou** [Isynopoulos1/wedding#1]
**ACCEPTANCE CRITERIA**

You want to use references from this article
https://medium.com/@pascalokereke18/how-to-setup-a-react-project-with-vite-6c2130d3bce
and chat GPT

**TASKS**

- [x] Create a boostraped create react app with vite
- [x] Should be able to be launch locally with `npm run dev` 
- [x] Should have `styled-component` installed
- [x]  Should have a hello world page on the port `3000`

**Comment by erwanriou** [comment]
You need to tag me first for review. Then i approve :)

**Comment by Isynopoulos1** [comment]
@erwanriou done

**Comment by erwanriou** [comment]
@Isynopoulos1 please make to remove the `DS_store` file and also add it to the gitignore
![Screenshot from 2024-05-20 15-25-20](https://github.com/Isynopoulos1/wedding/assets/30130006/cc4aef9a-6622-453c-96ea-bc9df25e8679)

**Comment by Isynopoulos1** [comment]
I just added the DS_store to .gitignore file

**Comment by Isynopoulos1** [comment]
I deleted the DS file from github

**Comment by erwanriou** [comment]
Good job you can close the ticket!
