### ISSUE TITLE
Custom domain for github page

### ISSUE THREAD

**Issue by erwanriou** [Isynopoulos1/wedding#14]
**ACCEPTANCE CRITERIA**

we want our hello world page to appear on the custom domain we bought on google. For that we need to do a series of tasks

**TASKS**

- [x] based on this documentation https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site you want to configure an apex domain under the `page` config of github as explained in step 4.
- [x] In the google cloud console where you bought the domain go in the `Cloud DNS` section (you can use the search tool to access there but make sure you are under the correct `project`)
- [x] Once you find the domain there, you need to create a `CNAME` record there by clicking the button `Add Standard` like in this screenshot.

![Screenshot from 2024-05-29 13-05-39](https://github.com/Isynopoulos1/wedding/assets/30130006/a0ed8360-e68a-4567-bcbc-d7e1c4ec05ad)

and then add the value of `www` for the DNS name and the `Cannonical Name` of the current github page url

![Screenshot from 2024-05-29 13-06-42](https://github.com/Isynopoulos1/wedding/assets/30130006/6ff3070f-b19b-4b85-b9be-0eb86ad3da1e)

- [x] It might probably not work so you should try to setup the `base` config from the vite configuration  to `/` instead of `/wedding/`
