### ISSUE TITLE
Create the folder architecture for the app

### ISSUE THREAD

**Issue by erwanriou** [Isynopoulos1/wedding#2]
**ACCEPTANCE CRITERIA**

We want to create the proper setup in order to work efficiently in the app. Let's start with the folder architecture as it's a way to organize your code better

**TASKS**

- [x] Within `src` folder remove everything and create an `index.js` file with the following content

```js
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.js'

ReactDOM.createRoot(document.getElementById('root')).render(<App />)
```
- [x] Create a `App.js` file that return a hello world arrow function
- [x] Remplace the `main.jsx` by `index.js` in the `index.html` file at the line 11 
- [x] Make sure it work on the `localhost:3000`
- [x] Create a `components` folder
- [x] Delete the content of the `public` folder

**Comment by Isynopoulos1** [comment]
I completed the 2nd task, and is ready to review it

**Comment by erwanriou** [comment]
All good here!
