### ISSUE TITLE
Create the header section

### ISSUE THREAD

**Issue by erwanriou** [Isynopoulos1/wedding#24]
**ACCEPTANCE CRITERIA**

Let's start by creating the header section of the website based on your design references

https://www.figma.com/design/ZuyFE2DsQCsxOu8woyTPrn/isela-erwan?node-id=0-1&t=q4aTwALe68HsLqyP-1

**TASKS**

- [x] Make sure you create a new branch from develop using the new branch creation feature that you can find on the right sidebar of this issue
- [x] Create the header html component with the correct semantic (this will be an organism in the component structure)
- [x] Create the styling related to it
- [x] Make sure it is responsive
- [x] Submit a PR from your feature branch against develop
