### ISSUE TITLE
Create the hero section

### ISSUE THREAD

**Issue by erwanriou** [Isynopoulos1/wedding#27]
**ACCEPTANCE CRITERIA**

We want to create a hero section that will contain maybe a background image, a title and a CTA that lead directly to openning the modal of the form. I am not sure of the figma design since i don't have access to it but that are the items that would be required.

We want to also make sure to like the `how` link of the menu to this section of the page (use #id for that in the html)

**TASKS**

- [x] Create the `hero` section linked the the `how` id.
- [x] Style the content of it
- [x] Make sure to add an `onClick` event to the `button` CTA that would lead to open the modal of the form.
- [x] The `onClick` event should trigger an handleFunction called `handleModal` that for now should modify the boolean value a hook state to its contrary (ref to what we did in the header)
```js
const [modal, setModal] = useState(false)
```
Make sure to show a `hello world` content when the `modal` state is `true`

**Comment by Isynopoulos1** [comment]
I think is ready to review

**Comment by erwanriou** [comment]
I don't see any PR
