### ISSUE TITLE
Implement translations

### ISSUE THREAD

**Issue by erwanriou** [Isynopoulos1/wedding#29]
**ACCEPTANCE CRITERIA**
Implement translation with the library https://www.npmjs.com/package/react-redux-translates

**TASKS**
- [x] susccessfully implement https://www.npmjs.com/package/react-redux-translates
- [x] Add all the required translations in the json files
- [x] make sure all the content is translated
- [x] update the header function to be able to switch translations (you can use the function `setActiveLanguage` for that purpose)

**HINT**
the handleTranslation function should look like this
```js
   const handleLanguage = async language => {
    await setActiveLanguage(language?.code)
  }
```

**Comment by erwanriou** [comment]
PR is not merged?

**Comment by Isynopoulos1** [comment]
I just did it
