### ISSUE TITLE
Add fonts files

### ISSUE THREAD

**Issue by erwanriou** [Isynopoulos1/wedding#3]
**ACCEPTANCE CRITERIA**

Make sure that the fonts are added and working locally

**TASKS**

- [x] add the fonts woff format into a folder called `fonts` that should potentially be inside the `src` and make sure that it work with styled component. 
- [x] You want to create some sort of font-face file (ask chat gpt)
- [x] test all type of the font behavior (bold, italic, etc)

**Comment by Isynopoulos1** [comment]
this is ready to check

**Comment by erwanriou** [comment]
**few things to fix:**

- `.DS_Store` is not fixed. Please remove again and correctly add it to `.gitignore`. It is now  in several subfolder as `src` etc... Please check all.
![Screenshot from 2024-05-23 16-08-44](https://github.com/Isynopoulos1/wedding/assets/30130006/8e9e87d3-3f01-4296-8431-8e92c355ddb6)

- Make sure the `constants` are not in `styles` but in `utils` instead
- Remove the style folder and make sure that the content of `GlobalStyles.jsx` is instead in `App.styles.jsx`
- Remove unecessary comment on top of the file
- Make sure to now use `Test` as name but instead `GlobalStyles`.

**Comment by Isynopoulos1** [comment]
I fixed all the bugs now, I also changed to woff2 but the error is still appearing, I tried also with woff and was the same.

**Comment by erwanriou** [comment]
Did you checked in firefox and sarafi? Can you ask chatgpt? Check the import also i think this is wrong.

`'./src/fonts/Cammron-Bold.woff2'` probably more correct.

**Comment by Isynopoulos1** [comment]
I updated the project with the last changes
