### ISSUE TITLE
Implement backend connection

### ISSUE THREAD

**Issue by erwanriou** [Isynopoulos1/wedding#33]
**ACCEPTANCE CRITERIA**

With this task we want to finally implement the last task that is to connect the form with the backend. For this purpose i will leave here a few indications.

- endpoint: `https://us-central1-pacific-aurora-419610.cloudfunctions.net/wedding-backend`
- method: `POST`
- required content of the body: `firstName, lastName, email, isConfirmed, dietaryType, more`

**TASKS**

- [x] Within the `handleSubmit` function make sure it is an async function and then do a `fetch` post request on the endpoint provided where you inject the formData (state) into the body.
- [x] Try to test it (it should nor return a 200 and an email or a 400/500 with an error)
- [ ] Fix padding UI on the 2/3 section where image is way too near the text
