### ISSUE TITLE
Create a branch strategy and deployment

### ISSUE THREAD

**Issue by erwanriou** [Isynopoulos1/wedding#4]
**ACCEPTANCE CRITERIA**

We want to make sure the page deploy with github page automatically. For now we won't focus in having the specific required DNS `www.isela-erwan.com` but instead a random DNS generated by the github page. It should be `https://Isynopoulos1.github.io/wedding`

**TASKS**
- [x] Create a `develop` branch on top of `master`
- [x] Make sure that `develop` is the `default` branch in the github settings
- [x] Setup branch protection rules for `master` so that it cannot be merged without a PR and 1 approval
- [x] Install github page library `npm install gh-pages --save-dev` 
- [x] follow the **steps 4, 5 and 8** from this guide https://github.com/gitname/react-gh-pages You might have to select the `master` branch instead of `gh-pages` branch and the folder `/build` instead of `/root`. You can check the config you have in iselaweb
- [x] Check that the commit trigged a github action that should point to the defined url in the `package.json`
